# Работа с библиотекой numpy

In [3]:
import numpy as np

In [4]:
# 1. Создайте одномерный массив my_array, в котором по порядку все числа до 100, кратные 5
array1 = np.arange(100)
my_array = array1[array1%5 == 0]
print(my_array)

[ 0  5 10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]


In [5]:
# 2. Из полученного массива получить массив с кратными 10 числами
array2 = my_array[my_array%10 == 0]
print(array2)

[ 0 10 20 30 40 50 60 70 80 90]


In [7]:
# 3. Получить двумерный массив с двумя столбцами
array3 = np.array([[1,2],[3,4],[5,6]])
array3

array([[1, 2],
       [3, 4],
       [5, 6]])

In [8]:
# 4. Получите набор my_second_array, в котором все элементы меньше предыдущего исходного на 5
my_second_array = array3 - 5
my_second_array

array([[-4, -3],
       [-2, -1],
       [ 0,  1]])

In [11]:
# 5. Соедините массивы, полученные в п. 3.1 и 4.1, горизонтально. Используйте .T для транспонирования матрицы.
array5 = np.concatenate((array3,my_second_array), axis=1)
array5.T

array([[ 1,  3,  5],
       [ 2,  4,  6],
       [-4, -2,  0],
       [-3, -1,  1]])

In [23]:
# 6. Разделите 2 и 3 строку на 4 верхних строки my_array. Используйте .T для транспонирования матрицы

ValueError: operands could not be broadcast together with shapes (2,2) (4,2) 

In [ ]:
# 7. Оставить только те значения, которые не изменились после деления

In [26]:
# 8. Снова получить трехстрочный двумерный массив и поменять местами первую и третью строки
array8 = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
print(array8)
array8 = array8[::-1]
print(array8)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[7 8 9]
 [4 5 6]
 [1 2 3]]


In [30]:
# 9. Получить среднее, медиану и стандартное отклонение для каждой строки, используя команды np.mean(), np.median(), np.std().
array9 = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
np.mean(array9, axis=1)

array([2., 5., 8.])

In [31]:
np.median(array9, axis=1)

array([2., 5., 8.])

In [33]:
np.std(array9, axis=1)

array([0.81649658, 0.81649658, 0.81649658])

In [34]:
# 10. Сделать нормализацию на максимальное значение вдоль строк, поделив каждый элемент массива на max() вдоль строк.
normalized_array = array9 / np.max(array9, axis=1, keepdims=True)
normalized_array

array([[0.33333333, 0.66666667, 1.        ],
       [0.66666667, 0.83333333, 1.        ],
       [0.77777778, 0.88888889, 1.        ]])

# Работа с библиотекой pandas

In [1]:
import pandas as pd

In [2]:
# 1. Импортируйте данные из файла “Global Population Trends(2016-2022).csv”. 
df = pd.read_csv('global_population_trends.csv')
df

Country  Year Total Population Urban Population Rural Population  \
0     Afghanistan  2017                -                -                -   
1     Afghanistan  2018       36,686,784        9,353,296       27,333,488   
2     Afghanistan  2019       37,769,499        9,727,157       28,042,342   
3     Afghanistan  2020       38,972,230       10,142,913       28,829,317   
4     Afghanistan  2021       40,099,462       10,551,772       29,547,690   
...           ...   ...              ...              ...              ...   
1068     Zimbabwe  2017                -                -                -   
1069     Zimbabwe  2018       15,052,184        4,848,158       10,204,026   
1070     Zimbabwe  2019       15,354,608        4,945,719       10,408,889   
1071     Zimbabwe  2020       15,669,666        5,052,214       10,617,452   
1072     Zimbabwe  2021       15,993,524        5,166,388       10,827,136   

     Population Density Life Expectancy  Birth Rate  Death Rate  \
0                    55            63.0      37.342       7.027   
1                    56            63.0      36.927       6.981   
2                    58            64.0      36.466       6.791   
3                    60            63.0      36.051       7.113   
4                     -            62.0      35.842       7.344   
...                 ...             ...         ...         ...   
1068                 38            61.0      32.516       8.266   
1069                 39            61.0      32.074       7.972   
1070                 40            61.0      31.518       8.043   
1071                 41            61.0      31.009       8.132   
1072                  -            59.0      30.537       9.057   

     Fertility Rate Infant Mortality Rate Growth Rate  
0             5.129                  49.4           -  
1             5.002                  47.8         3.0  
2              4.87                  46.3         3.0  
3              4.75                  44.8         3.0  
4             4.643                  43.4         3.0  
...             ...                   ...         ...  
1068          3.706                  39.5           -  
1069          3.659                  38.0         2.0  
1070          3.599                  37.1         2.0  
1071          3.545                  36.6         2.0  
1072          3.491                  35.7         2.0  

[1073 rows x 12 columns]

In [3]:
# 2. Считайте несколько первых записей таблицы (head())
df.head()

Country  Year Total Population Urban Population Rural Population  \
0  Afghanistan  2017                -                -                -   
1  Afghanistan  2018       36,686,784        9,353,296       27,333,488   
2  Afghanistan  2019       37,769,499        9,727,157       28,042,342   
3  Afghanistan  2020       38,972,230       10,142,913       28,829,317   
4  Afghanistan  2021       40,099,462       10,551,772       29,547,690   

  Population Density Life Expectancy  Birth Rate  Death Rate Fertility Rate  \
0                 55            63.0      37.342       7.027          5.129   
1                 56            63.0      36.927       6.981          5.002   
2                 58            64.0      36.466       6.791           4.87   
3                 60            63.0      36.051       7.113           4.75   
4                  -            62.0      35.842       7.344          4.643   

  Infant Mortality Rate Growth Rate  
0                  49.4           -  
1                  47.8         3.0  
2                  46.3         3.0  
3                  44.8         3.0  
4                  43.4         3.0

In [5]:
# 3. Определите размерность данного фрейма (shape())
df.shape

(1073, 12)

In [8]:
# 4. Выведите название заголовков столбцов фрейма (columns)
df.columns

Index(['Country', 'Year', 'Total Population', 'Urban Population',
       'Rural Population', 'Population Density', 'Life Expectancy',
       'Birth Rate', 'Death Rate', 'Fertility Rate', 'Infant Mortality Rate',
       'Growth Rate'],
      dtype='object')


In [9]:
# 5. Получите описание всех переменных (полей) (info())
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1073 entries, 0 to 1072
Data columns (total 12 columns):
 #   Column                 Non-Null Count  Dtype  
---  ------                 --------------  -----  
 0   Country                1073 non-null   object 
 1   Year                   1073 non-null   int64  
 2   Total Population       1073 non-null   object 
 3   Urban Population       1073 non-null   object 
 4   Rural Population       1073 non-null   object 
 5   Population Density     1073 non-null   object 
 6   Life Expectancy        1073 non-null   object 
 7   Birth Rate             1073 non-null   float64
 8   Death Rate             1073 non-null   float64
 9   Fertility Rate         1073 non-null   object 
 10  Infant Mortality Rate  1073 non-null   object 
 11  Growth Rate            1073 non-null   object 
dtypes: float64(2), int64(1), object(9)
memory usage: 100.7+ KB


In [10]:
# 6. Удалите строки, не содержащие значения в столбце «Total Population» - “-” 
df1 = df[df['Total Population'] != '-']
df1

Country  Year Total Population Urban Population Rural Population  \
1     Afghanistan  2018       36,686,784        9,353,296       27,333,488   
2     Afghanistan  2019       37,769,499        9,727,157       28,042,342   
3     Afghanistan  2020       38,972,230       10,142,913       28,829,317   
4     Afghanistan  2021       40,099,462       10,551,772       29,547,690   
6         Albania  2018        2,866,376        1,728,969        1,137,407   
...           ...   ...              ...              ...              ...   
1067       Zambia  2021       19,473,125        8,800,295       10,672,830   
1069     Zimbabwe  2018       15,052,184        4,848,158       10,204,026   
1070     Zimbabwe  2019       15,354,608        4,945,719       10,408,889   
1071     Zimbabwe  2020       15,669,666        5,052,214       10,617,452   
1072     Zimbabwe  2021       15,993,524        5,166,388       10,827,136   

     Population Density Life Expectancy  Birth Rate  Death Rate  \
1                    56            63.0      36.927       6.981   
2                    58            64.0      36.466       6.791   
3                    60            63.0      36.051       7.113   
4                     -            62.0      35.842       7.344   
6                   105            79.0      10.517       8.308   
...                 ...             ...         ...         ...   
1067                  -            61.0      34.511       6.973   
1069                 39            61.0      32.074       7.972   
1070                 40            61.0      31.518       8.043   
1071                 41            61.0      31.009       8.132   
1072                  -            59.0      30.537       9.057   

     Fertility Rate Infant Mortality Rate Growth Rate  
1             5.002                  47.8         3.0  
2              4.87                  46.3         3.0  
3              4.75                  44.8         3.0  
4             4.643                  43.4         3.0  
6              1.44                   8.3         0.0  
...             ...                   ...         ...  
1067          4.308                  40.2         3.0  
1069          3.659                  38.0         2.0  
1070          3.599                  37.1         2.0  
1071          3.545                  36.6         2.0  
1072          3.491                  35.7         2.0  

[864 rows x 12 columns]

In [11]:
# 7. Получите описательную статистику по переменным (например, max(), min(), describe())
df.max()

Country                    Zimbabwe
Year                           2021
Total Population             99,258
Urban Population         99,876,265
Rural Population            998,397
Population Density               99
Life Expectancy                85.0
Birth Rate                   46.351
Death Rate                     21.7
Fertility Rate                7.084
Infant Mortality Rate           9.9
Growth Rate                     5.0
dtype: object

In [12]:
df.min()

Country                  Afghanistan
Year                            2017
Total Population                   -
Urban Population                   -
Rural Population                   -
Population Density                 -
Life Expectancy                    -
Birth Rate                       0.0
Death Rate                       0.0
Fertility Rate                     -
Infant Mortality Rate              -
Growth Rate                        -
dtype: object

In [13]:
df.describe()

Year   Birth Rate   Death Rate
count  1073.000000  1073.000000  1073.000000
mean   2019.013048    18.801519     7.841907
std       1.410190     9.903449     2.973418
min    2017.000000     0.000000     0.000000
25%    2018.000000    10.620000     6.067000
50%    2019.000000    16.025000     7.396000
75%    2020.000000    25.921000     9.313000
max    2021.000000    46.351000    21.700000

In [15]:
# 8. Выполните сортировку данных по нескольким критериям
df2 = df.sort_values(by='Total Population', ascending=False)
df2

Country  Year Total Population Urban Population Rural Population  \
832   Seychelles  2021           99,258           57,542           41,716   
831   Seychelles  2020           98,462           56,661           41,801   
830   Seychelles  2019           97,625           55,762           41,863   
1047     Vietnam  2021       97,468,029       37,088,534       60,379,495   
829   Seychelles  2018           96,762           54,855           41,907   
...          ...   ...              ...              ...              ...   
591        Malta  2017                -                -                -   
586         Mali  2017                -                -                -   
581     Maldives  2017                -                -                -   
576     Malaysia  2017                -                -                -   
536      Liberia  2017                -                -                -   

     Population Density Life Expectancy  Birth Rate  Death Rate  \
832                   -            73.0      16.800       9.300   
831                 214            77.0      15.800       6.800   
830                 212            74.0      16.400       8.100   
1047                  -            74.0      15.008       7.317   
829                 210            73.0      17.100       8.400   
...                 ...             ...         ...         ...   
591               1,462            82.0       9.200       7.600   
586                  16            59.0      43.378       9.637   
581               1,575            80.0      16.126       2.784   
576                  97            75.0      16.355       5.132   
536                  50            61.0      33.151       8.954   

     Fertility Rate Infant Mortality Rate Growth Rate  
832            2.46                  12.0         1.0  
831            2.29                  12.2         1.0  
830            2.36                  12.4         1.0  
1047          1.944                  16.4         1.0  
829            2.41                  12.5         1.0  
...             ...                   ...         ...  
591            1.26                   5.6           -  
586           6.251                  67.3           -  
581           1.845                   7.1           -  
576           1.929                   6.9           -  
536           4.396                  62.1           -  

[1073 rows x 12 columns]

In [19]:
# 9. Выведите название страны, которая имеет максимальную численность населения
df3 = df[df['Total Population'] == df['Total Population'].max()]
df3

Country  Year Total Population Urban Population Rural Population  \
832  Seychelles  2021           99,258           57,542           41,716   

    Population Density Life Expectancy  Birth Rate  Death Rate Fertility Rate  \
832                  -            73.0        16.8         9.3           2.46   

    Infant Mortality Rate Growth Rate  
832                  12.0         1.0

In [22]:
# 10. Выведите название страны, которая имеет минимальную численность населения
df4 = df1[df1['Total Population'] == df1['Total Population'].min()]
df4

Country  Year Total Population Urban Population Rural Population  \
257  Djibouti  2018        1,057,198          822,257          234,941   

    Population Density Life Expectancy  Birth Rate  Death Rate Fertility Rate  \
257                 46            63.0      22.982       8.347          2.929   

    Infant Mortality Rate Growth Rate  
257                  50.3         2.0

In [23]:
# 11. Экспорт фрейма в MS Excel
df.to_excel(r'C:\Users\User\OneDrive\Рабочий стол\AIN-2-21\№5 семестр\Введение в большие данные и машинное обучение\Лабораторная работа №2\mydata.xlsx')